#!/usr/bin/env php
<?php
/* Copyright 2024 Romain "Artefact2" Dal Maso <romain.dalmaso@artefact2.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

pcntl_async_signals(false);

$config = json_decode(file_get_contents($argv[1] ?? __DIR__.'/config.json'), true);
if(!is_array($config)) {
	fprintf(STDERR, "%s: no config file; please copy config.json.example to config.json\n", $argv[0]);
	die(1);
}
$config['version'] = trim(shell_exec('git -C '.escapeshellarg(__DIR__).' describe --always --abbrev=7'));
$runtime_dir = getenv('XDG_RUNTIME_DIR');
if(!$runtime_dir || !is_dir($runtime_dir) || !is_writable($runtime_dir)) {
	$runtime_dir = sys_get_temp_dir();
	fprintf(STDERR, "%s: XDG_RUNTIME_DIR unset or incorrect, falling back to %s\n", $argv[0], $runtime_dir);
}
$config['heartbeat_path'] = $runtime_dir.'/horde-bridge.'.posix_getpid();

function msg(...$args): void {
	$fmt = array_shift($args);
	$fmt = "================= ".$fmt;
	fprintf(STDERR, $fmt, ...$args);
}

function spawn_task(callable $t): int {
	if(($pid = pcntl_fork()) !== 0) {
		return $pid;
	}

	die((int)$t());
}

function post(string $uri, array $json, array $headers = []): array|false {
	array_unshift($headers, 'Content-Type: application/json');
	$ctx = stream_context_create([
		'http' => [
			'method' => 'POST',
			'header' => implode("\r\n", $headers),
			'content' => json_encode($json),
			'timeout' => 300,
		],
	]);
	$ans = file_get_contents($uri, false, $ctx);
	if($ans !== false) {
		$ans = json_decode($ans, true);
	}
	return $ans;
}

$server_pid = spawn_task(function() use($config) {
	/* Ignore termination signals, let our parent KILL us when pending requests have completed */
	pcntl_signal(SIGTERM, SIG_IGN);
	pcntl_signal(SIGINT, SIG_IGN);
	pcntl_signal(SIGHUP, SIG_IGN);

	msg("spawning llama.cpp server\n");
	chdir(__DIR__);
	$cmd = $config['server_command'];
	$cmd .= ' --host 127.0.0.1 --port '.$config['server_port'];
	if($config['server_slots'] > 1) {
		$cmd .= ' -np '.$config['server_slots'];
	}
	$cmd .= ' --log-disable >/dev/null'; /* For privacy and legal deniability */
	passthru($cmd, $ret_code);
	return $ret_code;
});

do {
	sleep(2);
	$status = @json_decode(file_get_contents("http://127.0.0.1:".$config['server_port']."/health"), true);
} while(($status['status'] ?? "error") !== "ok");
msg("server loaded ok\n");

$hb_last_ts = microtime(true);
file_put_contents($config['heartbeat_path'], json_encode([
	'start' => [ $hb_last_ts, 0, 0 ],
	'since' => [ $hb_last_ts, 0, 0 ],
]));

$workers = [];
for($i = 0; $i < $config['workers']; ++$i) {
	$work = function() use($config, $i) {
		$generation = post($config['horde_root'].'/api/v2/generate/text/pop', [
			'bridge_agent' => 'horde-bridge-lcpp-server/'.$config['version'],
			'name' => $config['worker_name'],
			'models' => [ $config['advertised_model'] ],
			'max_length' => $config['advertised_max_length'],
			'max_context_length' => $config['advertised_max_context_length'],
			'priority_usernames' => $config['priority_usernames'],
			'softprompts' => [],
			'threads' => $config['advertised_threads'],
			'amount' => 1,
		], ['apikey: '.$config['worker_api_key']]);
		if(!isset($generation['payload']['prompt'])) {
			msg("got unexpected generation request: %s\n", json_encode($generation));
			sleep(5);
			return 0;
		}

		$payload = array_merge([
			'singleline' => false,
			'stop_sequence' => [],
			'sampler_order' => [6,0,1,3,4,2,5],
			'max_length' => 0,
			'max_context_length' => 0,
			'rep_pen' => 1.1,
			'rep_pen_range' => 64,
			'temperature' => 0.8,
			'tfs' => 1.0,
			'top_k' => 0,
			'top_p' => 0.95,
			'typical' => 1.0,
			'min_p' => 0.05,
			'dynatemp_range' => 0.0,
			'dynatemp_exponent' => 1.0,
		], $generation['payload']);

		if($payload['singleline']) {
			$payload['stop_sequence'][] = "\n";
			$payload['stop_sequence'][] = "\r\n";
		}

		if(($generation['payload']['top_a'] ?? 0) > 0) {
			msg("request %s: ignoring top_a sampler\n", $generation['id']);
		}
		if($payload['rep_pen'] > 1 && $payload['rep_pen_range'] > 0 && $payload['sampler_order'][0] !== 6) {
			msg("request %s: ignoring rep_pen sampler order\n", $generation['id']);
		}

		$ans = post('http://127.0.0.1:'.$config['server_port'].'/completion', [
			'prompt' => $payload['prompt'],
			'cache_prompt' => true,
			'n_predict' => $n_predict = min($config['advertised_max_length'], $payload['max_length']),
			'n_keep' => $n_keep = min($config['advertised_max_context_length'], $payload['max_context_length']),
			'repeat_penalty' => $payload['rep_pen'],
			'repeat_last_n' => $payload['rep_pen_range'],
			/* XXX: rep_pen_slope */
			'temperature' => $payload['temperature'],
			'tfs_z' => $payload['tfs'],
			/* XXX: top_a */
			'top_k' => $payload['top_k'],
			'top_p' => $payload['top_p'],
			'typical_p' => $payload['typical'],
			'min_p' => $payload['min_p'],
			/* XXX: default_badwordsids */
			'stop' => $payload['stop_sequence'],
			'dynatemp_range' => $payload['dynatemp_range'],
			'dynatemp_exponent' => $payload['dynatemp_exponent'],
			'samplers' => (function() use($payload) {
				/* from lite.koboldai.net: 0=topk, 1=topa, 2=topp/minp, 3=tfs, 4=typ, 5=temp, 6=reppen */
				/* https://github.com/ggerganov/llama.cpp/blob/master/common/common.cpp#L1137 */
				/* XXX: no top_a, rep_pen is always first */
				$samplers = [];
				foreach($payload['sampler_order'] as $s) {
					if($s === 0 && $payload['top_k'] > 0) {
						$samplers[] = 'top_k';
					} else if($s === 2) {
						if($payload['top_p'] < 1) {
							$samplers[] = 'top_p';
						}
						if($payload['min_p'] > 0) {
							$samplers[] = 'min_p';
						}
					} else if($s === 3 && $payload['tfs'] < 1.0) {
						$samplers[] = 'tfs_z';
					} else if($s === 4 && $payload['typical'] < 1.0) {
						$samplers[] = 'typical_p';
					} else if($s === 5) {
						$samplers[] = 'temperature';
					}
				}
				return $samplers;
			})(),
			'slot' => crc32(substr($payload['prompt'], 0, 128)) % $config['server_slots'],
		]);
		if(!isset($ans['content'])) {
			msg("unexpected reply from llama.cpp server: %s\n",
			    json_encode($ans));
			return 1;
		}

		$horde_ans = post($config['horde_root'].'/api/v2/generate/text/submit', [
			'id' => $generation['id'],
			'generation' => $ans['content'],
			'state' => 'ok',
		], ['apikey: '.$config['worker_api_key']]);
		if(!isset($horde_ans['reward'])) {
			msg("unexpected reply from /submit: %s\n",
			    json_encode($horde_ans));
			return 1;
		}

		printf("worker %d submitted %s, evaluated %d/%d (%.1fT/s) and predicted %d/%d (%.1fT/s) tokens, got %.2f kudos\n",
		       $i,
		       $generation['id'],
		       $ans['timings']['prompt_n'], $n_keep,
		       $ans['timings']['prompt_per_second'],
		       $ans['timings']['predicted_n'], $n_predict,
		       $ans['timings']['predicted_per_second'],
		       $horde_ans['reward']);

		spawn_task(function() use($config, $horde_ans) {
			$fp = fopen($config['heartbeat_path'], 'c+');
			flock($fp, LOCK_EX);
			$hb = json_decode(fgets($fp), true);
			rewind($fp);
			ftruncate($fp, 0);
			foreach($hb as $k => &$v) {
				$v[1] += 1;
				$v[2] += $horde_ans['reward'];
			}
			fwrite($fp, json_encode($hb));
			fclose($fp);
			return 0;
		});

		return 0;
	};

	$workers[] = spawn_task(function() use($config, $work) {
		$stop = false;
		$terminate = function() use(&$stop) {
			$stop = true;
		};
		pcntl_signal(SIGTERM, $terminate);
		pcntl_signal(SIGINT, $terminate);
		pcntl_signal(SIGHUP, $terminate);
		while($stop === false) {
			if($work() !== 0) {
				return 1;
			}
			pcntl_signal_dispatch();
		}
		return 0;
	});
}
msg("spawned %d worker processes\n", $config['workers']);

$stop = false;
$terminate = function() use(&$stop, $config, $workers, $server_pid) {
	msg("got termination signal, waiting for current generation(s) to end...\n");
	$stop = true;
	foreach($workers as $i => $pid) {
		pcntl_waitpid($pid, $status);
		msg("worker %d exited with code %d\n", $i, $status);
	}
	unlink($config['heartbeat_path']);
	posix_kill(0, SIGKILL);
};
pcntl_signal(SIGTERM, $terminate);
pcntl_signal(SIGINT, $terminate);
pcntl_signal(SIGHUP, $terminate);

while($stop === false) {
	foreach($workers as $pid) {
		if(pcntl_waitpid($pid, $status, WNOHANG) !== 0) {
			msg("one of our children exited abnormally, exiting\n");
			$terminate();
		}
	}
	pcntl_signal_dispatch();
	sleep(5);

	if(($ts = microtime(true)) - $hb_last_ts >= 300) {
		$fp = fopen($config['heartbeat_path'], 'c+');
		flock($fp, LOCK_EX);
		$hb = json_decode(fgets($fp), true);
		msg("heartbeat: %.1fkudos/hr, %.1freqs/hr since start, %.1fkudos/hr, %.1freqs/hr in the last 5 minutes\n",
		    3600 * $hb['start'][2] / ($ts - $hb['start'][0]),
		    3600 * $hb['start'][1] / ($ts - $hb['start'][0]),
		    3600 * $hb['since'][2] / ($ts - $hb['since'][0]),
		    3600 * $hb['since'][1] / ($ts - $hb['since'][0])
		);
		$hb['since'] = [ $ts, 0, 0 ];
		$hb_last_ts = $ts;
		rewind($fp);
		ftruncate($fp, 0);
		fwrite($fp, json_encode($hb));
		fclose($fp);
	}
}
